name: chroot archlinux/loongarch64

on:
  workflow_dispatch:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - run: id

        #- run: sudo apt-get -y update
        #- run: sudo apt-get -y install curl qemu-user-static

        #- run: dpkg -L qemu-user-static
        #- run: ls /usr/bin/qemu-*

      - run: curl -L -o bsdtar https://github.com/leleliu008/bsdtar.exe/releases/download/2025.06.26/bsdtar-3.7.7-linux-x86_64.release
      - run: chmod +x   bsdtar

      - run: curl -LO https://mirrors.nju.edu.cn/loongarch/archlinux/iso/latest/archlinux-bootstrap-loong64.tar.gz
      - run: install -d archlinux-loongarch64-rootfs
      - run: ./bsdtar xvf archlinux-bootstrap-loong64.tar.gz -C archlinux-loongarch64-rootfs --strip-components=1

      - run: sudo install -g `id -g` -o `id -u` /etc/resolv.conf                 archlinux-loongarch64-rootfs/etc/
        #- run: sudo install -g `id -g` -o `id -u` /usr/bin/qemu-loongarch64-static archlinux-loongarch64-rootfs/

      - run: sudo mount -o bind  /dev archlinux-loongarch64-rootfs/dev
      - run: sudo mount -t proc  none archlinux-loongarch64-rootfs/proc
      - run: sudo mount -t sysfs none archlinux-loongarch64-rootfs/sys

      - run: sudo mount --bind archlinux-loongarch64-rootfs archlinux-loongarch64-rootfs

      - run: |
          cat > archlinux-loongarch64-rootfs/run.sh <<EOF
          uname -a
          id
          pwd

          pacman -Syy --noconfirm
          pacman -S   --noconfirm gcc base-devel

          curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg

          export GITHUB_ACTIONS=true

          ./ppkg setup
          ./ppkg update
          ./ppkg install uctags
          ./ppkg bundle  uctags
          EOF

      - run: docker run --rm --privileged zhangguanzhang/qemu-user-static --reset -p yes

      - run: sudo chroot archlinux-loongarch64-rootfs uname -m
      - run: sudo chroot archlinux-loongarch64-rootfs /bin/sh -ex run.sh
