name: chroot-alpine

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target-arch: [loongarch64, x86_64, aarch64, riscv64, ppc64le, s390x, armhf]

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - run: |
          cat > run.sh <<EOF
          set -ex
          uname -a
          id
          pwd

          export GITHUB_ACTIONS=true

          ./ppkg setup
          ./ppkg update
          ./ppkg install sysinfo --static
          ./ppkg bundle  sysinfo .tar.xz
          ~/.ppkg/installed/linux-*/sysinfo/bin/sysinfo
          EOF

      - run: curl -LO https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/master/alpine-chroot-install
      - run: chmod +x alpine-chroot-install
      - run: sudo ./alpine-chroot-install -d /alpine -a ${{ matrix.target-arch }}
      - run: /alpine/enter-chroot /bin/sh run.sh
      - run: ls -l
      - run: /alpine/destroy
      - run: ls -l

      - uses: actions/upload-artifact@v4
        with:
          name: sysinfo---linux-${{ matrix.target-arch }}.tar.xz
          path: sysinfo-*.tar.xz
