name: chroot alpine/riscv64

on:
  workflow_dispatch:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > test.c <<EOF
          #include<linux/limits.h>
          int main() {
            char p[PATH_MAX];
            p[0] = '/';
            p[1] = '\0';
            return 0;
          }
          EOF

      - run: |
          cat > run.sh <<EOF
          set -ex
          uname -a
          id
          pwd

          apk update
          apk add g++ libc-dev linux-headers rust cargo

          cc -flto -Os -std=c99 test.c

          find / -name 'libgcc*'
          nm /usr/lib/gcc/riscv64-alpine-linux-musl/14.2.0/libgcc_eh.a
          nm /usr/lib/gcc/riscv64-alpine-linux-musl/14.2.0/libgcc.a

          wget https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
          chmod a+x ppkg

          export GITHUB_ACTIONS=true

          ./ppkg setup
          ./ppkg update
          ./ppkg install b3sum --static
          ./ppkg bundle  b3sum .tar.xz
          EOF

      - run: curl -LO https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/master/alpine-chroot-install
      - run: chmod +x alpine-chroot-install
      - run: sudo ./alpine-chroot-install -d /alpine -a riscv64 -p wget -p g++
      - run: /alpine/enter-chroot sh run.sh
      - run: ls -l
      - run: /alpine/destroy
      - run: ls -l

      - uses: actions/upload-artifact@v4
        with:
          name: b3sum---linux-riscv64.release.tar.xz
          path: b3sum-*-linux-riscv64.release.tar.xz
