name: Debian GNU/Linux

on:
  push:
    branches: [ test-xargs ]
  pull_request:
    branches: [ test-xargs ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['8.11', '9.13', '10.7']

    container: debian:${{ matrix.tag }}

    steps:
      - run: |
          [ $(head -c 4 /proc/self/exe) = $(printf '\177ELF') ]
