name: docker loongarch64

on:
  workflow_dispatch:

jobs:

  # https://github.com/loong64/docker-library
  # https://github.com/loongarchlinux
  # https://hub.docker.com/r/openeuler/openeuler/tags

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image: ['ghcr.io/loong64/alpine:3.22', 'ghcr.io/loong64/debian:trixie', 'ghcr.io/loongarchlinux/archlinux:latest', 'openeuler/openeuler:24.03']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - run: |
          cat > run.sh <<EOF
          set -ex
          uname -a
          id
          pwd

          export GITHUB_ACTIONS=true

          ./ppkg setup
          ./ppkg update
          ./ppkg install sysinfo
          ./ppkg bundle  sysinfo .tar.xz
          ~/.ppkg/installed/linux-*/sysinfo/bin/sysinfo
          EOF

      - run: docker run --rm --privileged ghcr.io/loong64/binfmt --install all
      - run: docker run -v $PWD:/root -w /root --platform linux/loong64 ${{ matrix.image }} /bin/sh run.sh
