# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: DragonFlyBSD

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['6.4.0']

    steps:
      - uses: actions/checkout@v4

      - run: ls

      - uses: vmactions/dragonflybsd-vm@v1
        with:
          release: "${{ matrix.version }}"
          usesh: true
          sync: rsync
          copyback: true
          run: |
            echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
            set -x
            uname -s
            uname -m
            uname -r
            cat /etc/os-release
            id
            pwd
            ls /usr/bin
            ls /usr/local
            ls /usr/local/bin
            pkg update
            pkg install -y gcc11 go122
            ls /usr/bin
            ls /usr/local
            ls /usr/local/bin
            ls /usr/libexec/
            ls /usr/libexec/gcc80/
            command -v gcc
            command -v g++
            echo "$PATH"

      - run: ls

  dragonflybsd:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['6.4']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - uses: vmactions/dragonflybsd-vm@v1
        with:
          release: "${{ matrix.version }}.0"
          usesh: true
          sync: rsync
          copyback: true
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            ./ppkg setup
            ./ppkg update
            ./ppkg install dragonflybsd-${{ matrix.version }}-x86_64/uppm@0.15.4 --static
            ./ppkg bundle  dragonflybsd-${{ matrix.version }}-x86_64/uppm@0.15.4 .tar.xz

      - uses: actions/upload-artifact@v4
        with:
          name: uppm---dragonflybsd-${{ matrix.version }}-x86_64.release.tar.xz
          path: uppm-*-dragonflybsd-${{ matrix.version }}-x86_64.release.tar.xz
