# Copyright: 2022 fpliu
# License: GPL-2.0-or-later

name: DragonFlyBSD

on:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['6.4.0']

    steps:
      - uses: actions/checkout@v5

      - run: ls

      - uses: vmactions/dragonflybsd-vm@v1
        with:
          release: "${{ matrix.version }}"
          usesh: true
          sync: rsync
          copyback: true
          run: |
            echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
            set -x

            uname -s
            uname -m
            uname -r

            cat /etc/os-release

            id
            pwd

            ls /usr/bin
            ls /usr/local
            ls /usr/local/bin

            pkg update
            pkg install -y gcc11 go122

            ls /usr/bin
            ls /usr/local
            ls /usr/local/bin
            ls /usr/libexec/
            ls /usr/libexec/gcc80/

            command -v gcc
            command -v g++

            echo "$PATH"

            find / -name curl

      - run: ls


  ppkg:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['6.4']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - run: curl -LO https://github.com/leleliu008/uppm-package-repository-dragonflybsd-6.4-x86_64/releases/download/2023.12.04/curl-8.3.0-dragonflybsd-6.4-x86_64.tar.xz
      - run: tar xvf curl-8.3.0-dragonflybsd-6.4-x86_64.tar.xz --strip-components=1
      - run: rm -rf include/ lib/ share/

      - uses: vmactions/dragonflybsd-vm@v1
        with:
          release: "${{ matrix.version }}.0"
          usesh: true
          sync: rsync
          copyback: true
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            export PATH="$PWD/bin:$PATH"

            run ./ppkg setup
            run ./ppkg update
            run ./ppkg install dragonflybsd-${{ matrix.version }}-x86_64/uppm@0.15.4 --static
            run ./ppkg bundle  dragonflybsd-${{ matrix.version }}-x86_64/uppm@0.15.4 .tar.xz

      - uses: actions/upload-artifact@v6
        with:
          name: uppm---dragonflybsd-${{ matrix.version }}-x86_64.release.tar.xz
          path: uppm-*-dragonflybsd-${{ matrix.version }}-x86_64.release.tar.xz
