name: Fedora

on:
  push:
    branches: [ test-xargs ]
  pull_request:
    branches: [ test-xargs ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [28, 30, 33, latest, rawhide]

    container: fedora:${{ matrix.tag }}

    steps:
      - run: |
          [ $(head -c 4 /proc/self/exe) = $(printf '\177ELF') ]
