name: Gentoo

on:
  push:
    branches: [ test-xargs ]
  pull_request:
    branches: [ test-xargs ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    container: madhacking/gentoo

    steps:
      - run: |
          [ $(head -c 4 /proc/self/exe) = $(printf '\177ELF') ]
