name: Haiku

on:
  workflow_dispatch:

jobs:
  haiku1:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['r1beta5']

    steps:
      - uses: cross-platform-actions/action@master
        with:
          operating_system: haiku
          version: ${{ matrix.version }}
          shell: bash
          run: |
            echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
            set -x

            uname -s
            uname -m
            uname -r

            [ -f /etc/os-release ] && cat /etc/os-release

            id
            pwd

            echo "$PATH"

            pkgman --help
            pkgman --version

            pkgman refresh

            pkgman search gcc
            pkgman search git
            pkgman search curl
            pkgman search tar
            pkgman search sed
            pkgman search awk
            pkgman search m4
            pkgman search pkg-config
            pkgman search libarchive
            pkgman search bash
            pkgman search go
            pkgman search golang
            pkgman search jq
            pkgman search yq
            pkgman search grep
            pkgman search find
            pkgman search diff
            pkgman search tree
            pkgman search make
            pkgman search core
            pkgman search utils

            pkgman install bash coreutils findutils gawk sed grep tree jq git curl gcc libarchive_tools

            command -v gcc
            command -v g++
            command -v git
            command -v go || true

            curl -LO https://raw.githubusercontent.com/leleliu008/test/master/print-needed.c
            gcc -flto -Os -std=gnu99 print-needed.c
            ./a.out a.out


  haiku2:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['r1beta5']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - uses: cross-platform-actions/action@master
        with:
          operating_system: haiku
          version: ${{ matrix.version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run ./ppkg about
            run ./ppkg setup --syspm
            run ./ppkg sysinfo
            run ./ppkg update
            run ./ppkg install haiku-${{ matrix.version }}-x86_64/uppm@0.15.4 --static
            run ./ppkg bundle  haiku-${{ matrix.version }}-x86_64/uppm@0.15.4 .tar.xz

      - uses: actions/upload-artifact@v6
        with:
          name: uppm---haiku-${{ matrix.version }}-x86_64.release.tar.xz
          path: uppm-*-haiku-${{ matrix.version }}-x86_64.release.tar.xz
