name: macOS elf.h

on:
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [26, 15, 14]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v5
        with:
          repository: leleliu008/elftool

      - run: curl -L -o src/elf.h 'https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=elf/elf.h;hb=HEAD'

      - run: cc -std=gnu99 -Os -flto -Wl,-s -o elftool src/*.c src/_elf/*.c -Isrc

      - run: ./elftool --help
      - run: ./elftool --version

      - run: curl -LO https://github.com/leleliu008/uppm-package-repository-linux-s390x-glibc/releases/download/2022.10.08/bzip2-1.0.8-linux-s390x-glibc.tar.xz
      - run: tar xf *.tar.xz --strip-components=1

      - run: ./elftool print-interpreter bin/bzip2
      - run: ./elftool print-interpreter lib/libbz2.so
      - run: ./elftool print-soname      lib/libbz2.so
      - run: ./elftool print-rpath       lib/libbz2.so
