name: macOS

on:
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [26, 15, 14]

    runs-on: macos-${{ matrix.version }}

    steps:
      - run: curl -LO https://github.com/leleliu008/ndk-pkg/releases/download/ndk-pkg-core-2026.03.12/ndk-pkg-core-2026.03.12-macos-${{ matrix.version }}.0-arm64.tar.xz
      - run: tar vxf *.tar.xz --strip-components=1

      - run: ./uppm about
      - run: ./uppm sysinfo
      - run: ./uppm update

      - run: ls ~/.uppm/repos.d/official-core/formula/

      - run: ./uppm install android-sdk
