name: macOS

on:
  push:
    branches: [ test-xargs ]
  pull_request:
    branches: [ test-xargs ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [10.15, 11]

    runs-on: macos-${{ matrix.version }}

    steps:
      - run: |
          printf '%s\n' 'a.rst.1 b.rst.1 c.rst.1' | xargs -I{} basename {} .rst.1
