name: MidnightBSD

on:
  workflow_dispatch:

jobs:
  midnightbsd1:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['4.0.4']

    steps:
      - uses: cross-platform-actions/action@master
        with:
          operating_system: midnightbsd
          version: ${{ matrix.version }}
          shell: bash
          run: |
            echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
            set -x

            uname -s
            uname -m
            uname -r

            cat /etc/os-release

            id
            pwd

            mport help || true

            mport list
            mport search curl
            mport search git
            mport search gcc
            mport search bash
            mport search coreutils
            mport search findutils
            mport search awk
            mport search sed
            mport search grep
            mport search tree
            mport search jq
            mport search yq
            mport search go

            ls /usr/
            ls /usr/bin
            ls /usr/local
            ls /usr/local/bin

            sudo mport -f delete perl5
            sudo mport install bash coreutils findutils gawk gsed gnugrep tree jq yq go git curl gcc || true

            ls /usr/bin
            ls /usr/local
            ls /usr/local/bin
            ls /usr/libexec/

            command -v gcc
            command -v g++
            command -v git

            echo "$PATH"


  midnightbsd2:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['4.0.4']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - uses: cross-platform-actions/action@master
        with:
          operating_system: midnightbsd
          version: ${{ matrix.version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run ./ppkg about
            run ./ppkg setup --syspm
            run ./ppkg sysinfo
            run ./ppkg update
            run ./ppkg install midnightbsd-${{ matrix.version }}-x86_64/uppm@0.15.4 --static
            run ./ppkg bundle  midnightbsd-${{ matrix.version }}-x86_64/uppm@0.15.4 .tar.xz

      - uses: actions/upload-artifact@v6
        with:
          name: uppm---midnightbsd-${{ matrix.version }}-x86_64.release.tar.xz
          path: uppm-*-midnightbsd-${{ matrix.version }}-x86_64.release.tar.xz
