name: LinuxMint

on:
  push:
    branches: [ test-xargs ]
  pull_request:
    branches: [ test-xargs ]

jobs:
  test:
    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false
      matrix:
        tag: [19.3, 20.1]

    container: linuxmintd/mint${{ matrix.tag }}-amd64

    steps:
      - run: |
          printf '%s\n' 'a.rst.1 b.rst.1 c.rst.1' | xargs -I{} basename {} .rst.1
