name: build musl-libc with clang

on:
  workflow_dispatch:

jobs:

  glibc:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target-arch: [powerpc64le, loongarch64, aarch64, riscv64, s390x]

    steps:
      - run: sudo apt -y update
      - run: sudo apt -y install gcc-${{ matrix.target-arch }}-linux-gnu clang tree

      - run: curl -LO http://musl.libc.org/releases/musl-1.2.6.tar.gz
      - run: install -d musl/src/
      - run: tar xf *.tar.gz -C musl/src/ --strip-components=1
      - run: musl/src/configure --prefix="$PWD/musl/out" CC=${{ matrix.target-arch }}-linux-gnu-gcc
      - run: make -C musl/src/ ARCH=${{ matrix.target-arch }} CC=${{ matrix.target-arch }}-linux-gnu-gcc AS=${{ matrix.target-arch }}-linux-gnu-as AR=${{ matrix.target-arch }}-linux-gnu-ar RANLIB=${{ matrix.target-arch }}-linux-gnu-ranlib
      - run: make -C musl/src/ install
      - run: tree musl/out
