name: build musl-libc with clang

on:
  workflow_dispatch:

jobs:

  glibc:

    runs-on: ubuntu-26.04

    strategy:
      fail-fast: false
      matrix:
        target-arch: [powerpc64le, loongarch64, aarch64, riscv64, s390x]

    env:
      CC: ${{ matrix.target-arch }}-linux-gnu-gcc
      AR: ${{ matrix.target-arch }}-linux-gnu-ar
      RANLIB: ${{ matrix.target-arch }}-linux-gnu-ranlib

    steps:
      - run: cat /etc/os-release

      - run: sudo apt -y update
      - run: sudo apt -y install gcc-${{ matrix.target-arch }}-linux-gnu tree

      - run: curl -LO http://musl.libc.org/releases/musl-1.2.6.tar.gz
      - run: install -d src/musl/
      - run: tar xf *.tar.gz -C src/musl/ --strip-components=1

      - run: cd src/musl/ && ./configure --prefix=${{ github.workspace }}/sysroot --enable-wrapper=all
      - run: cd src/musl/ && make ARCH=${{ matrix.target-arch }}
      - run: cd src/musl/ && make install

      - run: tree ${{ github.workspace }}/sysroot

      - run: sudo apt-get -y update
      - run: sudo apt-get -y install automake autoconf pkg-config make gcc

      - name: build libiconv
        run: |
          install -d src/libiconv
          cd         src/libiconv
          curl -L -o src.tar.gz https://distfiles.macports.org/libiconv/libiconv-1.19.tar.gz
          tar xf     src.tar.gz --strip-components=1
          ./configure --host=${{ matrix.target-arch }}-unknown-linux-gnu --prefix=${{ github.workspace }}/sysroot --enable-extra-encodings --enable-static --disable-shared
          make V=1
          make install

      - uses: actions/checkout@v5
        with:
          repository: universal-ctags/ctags
          path: ctags

      - run: cd ctags && export -p && ./autogen.sh
      - run: cd ctags && ./configure --host=${{ matrix.target-arch }}-unknown-linux-gnu --enable-debugging || (cat config.log; exit 1)
      - run: cd ctags && make V=1

      - run: cd ctags && readelf -h ctags
      - run: cd ctags && readelf -d ctags

