name: OmniOS

on:
  workflow_dispatch:

jobs:
  omnios1:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['r151056', 'r151058']

    steps:
      - uses: cross-platform-actions/action@master
        with:
          operating_system: omnios
          version: ${{ matrix.version }}
          shell: bash
          run: |
            echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
            set -x

            uname -s
            uname -m
            uname -r

            cat /etc/os-release

            id
            pwd

            echo "$PATH"

            ls -l /usr/
            ls -l /usr/bin
            ls -l /usr/gcc
            ls -l /usr/gcc/14
            ls -l /usr/gcc/14/lib
            ls -l /usr/gnu
            ls -l /usr/gnu/bin

            pkg version
            pkg help
            pkg list

            pkg search gcc
            pkg search git
            pkg search bsdtar
            pkg search libarchive
            pkg search bash
            pkg search curl
            pkg search tree
            pkg search grep
            pkg search coreutils
            pkg search find
            pkg search awk
            pkg search sed
            pkg search jq
            pkg search go
            pkg search pkg-config
            pkg search m4
            pkg search perl

            pkg info bash
            pkg info gnu-coreutils
            pkg info gnu-findutils
            pkg info gnu-grep
            pkg info gnu-sed
            pkg info gawk
            pkg info tree
            pkg info curl
            pkg info git
            pkg info jq
            pkg info libarchive
            pkg info gcc14
            pkg info go-126

            sudo pkg install bash gnu-coreutils gnu-findutils gnu-sed gnu-grep gawk tree jq git curl libarchive gcc14 go-126

            command -v gcc
            command -v g++
            command -v git
            command -v bsdtar

            unset GOOS
            unset GOARCH

            curl -L -o yq.src.tar.gz https://github.com/mikefarah/yq/archive/refs/tags/v4.53.2.tar.gz
            install -d yq.src
            bsdtar xvf yq.src.tar.gz -C yq.src --strip-components=1
            go build -C yq.src -o ../bin/ -trimpath -ldflags '-s -w'
            bin/yq --version

  omnios2:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ['r151056', 'r151058']

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - uses: cross-platform-actions/action@master
        with:
          operating_system: omnios
          version: ${{ matrix.version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run ./ppkg about
            run ./ppkg setup --syspm
            run ./ppkg sysinfo
            run ./ppkg update
            run ./ppkg install omnios-${{ matrix.version }}-x86_64/uppm@0.15.4 --static
            run ./ppkg bundle  omnios-${{ matrix.version }}-x86_64/uppm@0.15.4 .tar.xz

      - uses: actions/upload-artifact@v6
        with:
          name: uppm---omnios-${{ matrix.version }}-x86_64.release.tar.xz
          path: uppm-*-omnios-${{ matrix.version }}-x86_64.release.tar.xz
