name: OpenBSD

on:
  workflow_run:
    workflows: ["FreeBSD"]
    types:
      - completed

jobs:
  test:
    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2

    - uses: leleliu008/github-actions-vagrant@v1
      with:
        mem: 2048
        box: generic/openbsd6
        run: |
            [ $(head -c 4 /proc/self/exe) = $(printf '\177ELF') ]
