name: OpenBSD

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ * ]

jobs:
  test:
    runs-on: macos-10.15
    
    steps:
    - uses: actions/checkout@v2

    - uses: leleliu008/github-actions-vagrant@v1
      with:
        mem: 2048
        box: generic/openbsd6
        run: |
          printf '%s\n' 'a.rst.1 b.rst.1 c.rst.1' | xargs -I{} basename {} .rst.1
