name: openSUSE Leap

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: [15.1]

    container: opensuse/leap:${{ matrix.tag }}

    steps:
      - run: zypper update  -y
      - run: zypper install -y git curl

      - uses: actions/checkout@v5

      - run: curl -v -LO https://curl.se/ca/cacert.pem

      - run: zypper help info

      - run: zypper info cmake
      - run: zypper info make
      - run: zypper info git

      - run: |
          zypper info cmake | sed -n '/Version        :/p' | sed 's/Version        : \(.*\)/\1/' | cut -d- -f1

      - run: |
          zypper info  make | sed -n '/Version        :/p' | sed 's/Version        : \(.*\)/\1/' | cut -d- -f1

      - run: |
          zypper info   git | sed -n '/Version        :/p' | sed 's/Version        : \(.*\)/\1/' | cut -d- -f1
