name: OpenBSD

on:
  push:
    branches: [ test-head-instead-of-hexdump ]
  pull_request:
    branches: [ test-head-instead-of-hexdump ]

jobs:
  test:
    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v2

    - uses: leleliu008/github-actions-vagrant@v1
      with:
        mem: 2048
        box: generic/openbsd6
        run: |
            [ $(head -c 4 /proc/self/exe) = $(printf '\177ELF') ]
