name: OpenBSD

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        openbsd-version: ['7.7', '7.6', '7.5', '7.4', '7.3', '7.2']

    steps:
      - uses: cross-platform-actions/action@master
        with:
          operating_system: openbsd
          version: ${{ matrix.openbsd-version }}
          shell: sh
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            set -ex

            id

            uname -r

            sudo pkg_add libarchive gawk gsed ggrep python%3.11

            ls /usr/local/
            ls /usr/local/bin/
            ls /usr/local/libexec/

            curl -LO https://github.com/fpliu1214/perl-distribution/releases/download/5.40.2/perl-5.40.2-openbsd-${{ matrix.openbsd-version }}-amd64.tar.xz
            install -d perl/
            bsdtar xf perl-5.40.2-openbsd-${{ matrix.openbsd-version }}-amd64.tar.xz -C perl/ --strip-components=1

            export PATH="$PWD/perl/bin:$PATH"

            perl -e 'print $^X'
            perl -V:prefix
            perl -V

            $PWD/perl/bin/perl -V:prefix
            $PWD/perl/bin/perl -V
