name: macOS perl

on:
  workflow_dispatch:

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [26, 15, 14]

    runs-on: macos-${{ matrix.version }}

    steps:
      - uses: actions/checkout@v5

        #- run: brew update
      - run: brew install coreutils findutils grep gnu-sed make

      - run: ./build.sh install --prefix="$PWD/out"
