name: NetBSD perl

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        netbsd-version: ['10.1', '10.0', '9.4', '9.3', '9.2']

    steps:
      - run: curl -LO https://curl.se/ca/cacert.pem

      - run: |
            case ${{ matrix.netbsd-version }} in
                10.*)
                    for x in 'bsdtar-3.8.1' 'grep-3.12' 'gsed-4.9' 'gmake-4.4.1' 'coreutils-9.4' 'findutils-4.9.0'
                    do
                        f="$x-netbsd-10.0-amd64.release.tar.xz"
                        curl -LO "https://github.com/leleliu008/uppm-package-repository-netbsd-10.0-amd64/releases/download/2025.07.25/$f"
                        tar xf "$f" --strip-components=1
                    done
                    ;;
                9.*)
                    for x in 'bsdtar-3.8.1' 'grep-3.12' 'gsed-4.9' 'gmake-4.4.1' 'coreutils-9.4' 'findutils-4.9.0'
                    do
                        f="$x-netbsd-9.2-amd64.release.tar.xz"
                        curl -LO "https://github.com/leleliu008/uppm-package-repository-netbsd-9.2-amd64/releases/download/2025.07.23/$f"
                        tar xf "$f" --strip-components=1
                    done
            esac

      - uses: cross-platform-actions/action@master
        with:
          operating_system: netbsd
          version: ${{ matrix.netbsd-version }}
          shell: bash
          run: |
            set -ex

            uname -r

            export SSL_CERT_FILE="$PWD/cacert.pem"
            export PATH="$PWD/bin:$PATH"

            install -d perl/

            curl -LO https://github.com/leleliu008/perl-distribution/releases/download/5.42.2/perl-5.42.2-netbsd-${{ matrix.netbsd-version }}-amd64.tar.xz
            bsdtar xf perl-*-amd64.tar.xz -C perl/ --strip-components=1

            export PATH="$PWD/perl/bin:$PATH"

            perl -e 'print $^X'
            perl -V:prefix
            perl -V

            $PWD/perl/bin/perl -e 'print $^X'
            $PWD/perl/bin/perl -V:prefix
            $PWD/perl/bin/perl -V

            export PERL="$PWD/perl/bin/perl"

            install -d openssl/
            install -d autoconf/
            install -d automake/
            install -d autotools/

            export PATH="$PWD/autotools/bin:$PATH"

            curl -LO https://ftp.gnu.org/gnu/autoconf/autoconf-2.73.tar.gz
            bsdtar xf autoconf-2.73.tar.gz -C autoconf/ --strip-components=1
            cd autoconf/
            ./configure --prefix="$PWD/../autotools"
            gmake
            gmake install

            cd ..

            curl -LO https://ftp.gnu.org/gnu/automake/automake-1.18.1.tar.xz
            bsdtar xf automake-1.18.1.tar.xz -C automake/ --strip-components=1
            cd automake/
            ./configure --prefix="$PWD/../autotools"
            gmake
            gmake install

            cd ..

            autotools/bin/autoconf --help
            autotools/bin/automake --help

            curl -LO https://github.com/openssl/openssl/releases/download/openssl-3.6.2/openssl-3.6.2.tar.gz
            bsdtar xf openssl-3.6.2.tar.gz -C openssl/ --strip-components=1
            cd openssl
            ./config --prefix="$PWD/../autotools"
            gmake build_libs
