name: ppkg-docker

on:
  workflow_dispatch:

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, alpine]
        arch: [amd64, arm64/v8, riscv64, ppc64le, s390x]

    runs-on: ubuntu-latest

    steps:
      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run ppkg setup
          run ppkg update
          run ppkg install xxd
          run ppkg bundle  xxd .tar.xz
          EOF

      - run: |
          case ${{ matrix.arch }} in
            amd64) ;;
            *)
              # https://github.com/multiarch/qemu-user-static
              docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          esac

      - run: docker run --platform linux/${{ matrix.arch }} -v $PWD:/root -w /root ghcr.io/leleliu008/ppkg/${{ matrix.os }} run.sh
