name: sccache test

on:
  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-26.04

    strategy:
      fail-fast: false
      matrix:
        target-arch: [powerpc64le, loongarch64, aarch64, riscv64, s390x]

    env:
      CC: ${{ github.workspace }}/launcher
      REALCC: /usr/bin/${{ matrix.target-arch }}-linux-gnu-gcc
      AR: /usr/bin/${{ matrix.target-arch }}-linux-gnu-ar
      RANLIB: /usr/bin/${{ matrix.target-arch }}-linux-gnu-ranlib
      CFLAGS: -fPIC
      LDFLAGS: -Wl,--as-needed
      PKG_CONFIG_PATH: ${{ github.workspace }}/sysroot/lib/pkgconfig
      SCCACHE_GHA_ENABLED: 'true'

    steps:
      - run: printf 'CFLAGS=%s -mlong-double-64\n' "$CFLAGS" >> "$GITHUB_ENV"
        if: matrix.target-arch == 'powerpc64le'
        # https://www.openwall.com/lists/musl/2022/06/29/1

      - id: musl-arch
        run: |
          if [ ${{ matrix.target-arch }} = powerpc64le ] ; then
            ARCH=powerpc64
          else
            ARCH=${{ matrix.target-arch }}
          fi
          printf 'ARCH=%s\n' "$ARCH" >> "$GITHUB_OUTPUT"

      - run: sudo apt -y update
      - run: sudo apt -y install gcc gcc-${{ matrix.target-arch }}-linux-gnu automake autoconf pkg-config cmake make qemu-user

      - run: command -v "$REALCC"
      - run: command -v "$AR"
      - run: command -v "$RANLIB"

      - uses: actions/checkout@v5
        with:
          repository: universal-ctags/ctags

      - uses: mozilla-actions/sccache-action@v0.0.11

      - run: |
          cat > launcher.c <<EOF
          #include <stdio.h>
          #include <stdlib.h>

          #include <unistd.h>

          int main(int argc, char* argv[]) {
              char * sccache = getenv("SCCACHE_PATH");

              if (sccache == NULL || sccache[0] == '\0') {
                  fprintf(stderr, "SCCACHE_PATH environment variable was not set.\n");
                  return 1;
              }

              /////////////////////////////////////

              char * cc = getenv("REALCC");

              if (cc == NULL || cc[0] == '\0') {
                  fprintf(stderr, "REALCC environment variable was not set.\n");
                  return 1;
              }

              /////////////////////////////////////

              int compile = 0;

              for (int i = 1; i < argc; i++) {
                  if (argv[i][0] == '-' && argv[i][1] == 'c' && argv[i][2] == '\0') {
                      compile = 1;
                      break;
                  }
              }

              if (compile == 0) {
                  argv[0] = cc;
                  execv (cc, argv);
                  perror(cc);
              } else {
                  char* args[argc + 2];

                  args[0] = sccache;
                  args[1] = cc;

                  for (int i = 1; i < argc; i++) {
                      args[i + 1] = argv[i];
                  }

                  args[argc + 1] = NULL;

                  //for (int i = 0; args[i] != NULL; i++) {
                  //    fprintf(stderr, "%s ", args[i]);
                  //}
                  //fprintf(stderr, "\n");

                  execv (sccache, args);
                  perror(sccache);
              }

              return 255;
          }
          EOF

      - run: gcc -Os -flto -Wl,-s -static -o launcher launcher.c

      - run: curl -LO https://archive.ubuntu.com/ubuntu/pool/universe/m/musl/musl_1.2.6.orig.tar.gz
      - run: install -d src/musl/
      - run: tar xf *.tar.gz -C src/musl/ --strip-components=1

      - run: cd src/musl/ && ./configure --prefix=${{ github.workspace }}/sysroot
      - run: cd src/musl/ && make -j2 ARCH=${{ steps.musl-arch.outputs.ARCH }}
      - run: cd src/musl/ && make install

      - run: printf 'CC=${{ github.workspace }}/sysroot/bin/musl-gcc\n' >> "$GITHUB_ENV"

      - name: build zlib
        run: |
          install -d src/libz
          cd         src/libz
          curl -L -o src.tar.gz https://distfiles.macports.org/zlib/zlib-1.3.2.tar.xz
          tar vxf    src.tar.gz --strip-components=1
          cmake -S . -B build.d -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/sysroot -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DZLIB_BUILD_TESTING=OFF -DZLIB_BUILD_STATIC=ON -DZLIB_BUILD_SHARED=OFF
          cmake --build build.d
          cmake --install build.d

      - name: build libiconv
        run: |
          install -d src/libiconv
          cd         src/libiconv
          curl -L -o src.tar.gz https://distfiles.macports.org/libiconv/libiconv-1.19.tar.gz
          tar xf     src.tar.gz --strip-components=1
          ./configure --host=${{ matrix.target-arch }}-unknown-linux-gnu --prefix=${{ github.workspace }}/sysroot --enable-extra-encodings --enable-static --disable-shared
          make -j2 V=1
          make install

      - name: build libxml2
        run: |
          install -d src/libxml2
          cd         src/libxml2
          curl -L -o src.tar.gz https://download.gnome.org/sources/libxml2/2.15/libxml2-2.15.3.tar.xz
          tar vxf    src.tar.gz --strip-components=1
          ./configure --host=${{ matrix.target-arch }}-unknown-linux-gnu --prefix=${{ github.workspace }}/sysroot --with-zlib --without-lzma --without-python --without-readline --without-coverage --enable-ipv6 --enable-static --disable-shared LIBS=-liconv || (cat config.log; exit 1)
          make -j2 V=1
          make install

      - name: build libyaml
        run: |
          install -d src/libyaml
          cd         src/libyaml
          curl -L -o src.tar.gz https://github.com/yaml/libyaml/releases/download/0.2.5/yaml-0.2.5.tar.gz
          tar vxf    src.tar.gz --strip-components=1
          ./configure --host=${{ matrix.target-arch }}-unknown-linux-gnu --prefix=${{ github.workspace }}/sysroot --enable-static --disable-shared
          make -j2 V=1
          make install

      - name: build jansson
        run: |
          install -d src/jansson
          cd         src/jansson
          curl -L -o src.tar.gz https://github.com/akheron/jansson/releases/download/v2.15.0/jansson-2.15.0.tar.gz
          tar vxf    src.tar.gz --strip-components=1
          cmake -S . -B build.d -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/sysroot -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_TESTING=OFF -DJANSSON_BUILD_SHARED_LIBS=OFF -DJANSSON_BUILD_DOCS=OFF -DJANSSON_COVERAGE=OFF -DJANSSON_EXAMPLES=OFF -DJANSSON_WITHOUT_TESTS=ON
          cmake --build build.d
          cmake --install build.d

      - name: build libpcre2
        run: |
          install -d src/libpcre2
          cd         src/libpcre2
          curl -L -o src.tar.gz https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.47/pcre2-10.47.tar.bz2
          tar vxf    src.tar.gz --strip-components=1
          cmake -S . -B build.d -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/sysroot -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_TESTING=OFF -DCMAKE_C_STANDARD=99 -DCMAKE_C_STANDARD_REQUIRED=ON -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DPCRE2_BUILD_PCRE2_8=ON -DPCRE2_BUILD_PCRE2_16=ON -DPCRE2_BUILD_PCRE2_32=ON -DPCRE2_BUILD_PCRE2GREP=OFF -DPCRE2_BUILD_TESTS=OFF -DPCRE2_SUPPORT_VALGRIND=OFF -DPCRE2_SUPPORT_UNICODE=ON -DPCRE2_SUPPORT_LIBZ=OFF -DPCRE2_SUPPORT_LIBBZ2=OFF -DPCRE2_SUPPORT_LIBEDIT=OFF -DPCRE2_SUPPORT_LIBREADLINE=OFF
          cmake --build build.d
          cmake --install build.d

      - run: ./autogen.sh
      - run: ./configure --host=${{ matrix.target-arch }}-unknown-linux-gnu --enable-debugging --enable-static || (cat config.log; exit 1)
      - run: make -j2 V=1

      - run: readelf -h ctags
      - run: readelf -d ctags

      - id: actual-hex
        run: |
          HEX=$(hexdump -n 20 -e '20/1 "%02X" "\n"' ctags)
          printf 'HEX=%s\n' "$HEX" >> "$GITHUB_OUTPUT"

      - id: expect-hex
        run: |
          case ${{ matrix.target-arch }} in
            powerpc64le) HEX=7F454C4602010100000000000000000002001500 ;;
            loongarch64) HEX=7F454C4602010100000000000000000002000201 ;;
            aarch64)     HEX=7F454C460201010000000000000000000200B700 ;;
            riscv64)     HEX=7F454C460201010000000000000000000200F300 ;;
            s390x)       HEX=7F454C4602020100000000000000000000020016 ;;
          esac
          printf 'HEX=%s\n' "$HEX" >> "$GITHUB_OUTPUT"

      - run: test ${{ steps.actual-hex.outputs.HEX }} = ${{ steps.expect-hex.outputs.HEX }}

        #- run: readelf -h /usr/bin/qemu-${{ matrix.target-arch }}
        #- run: readelf -d /usr/bin/qemu-${{ matrix.target-arch }}

      - run: ./ctags --help
      - run: ./ctags --version

      - run: make check V=1
      - run: make roundtrip
      - run: make tmain CI=1 CTAGS_DEP= READTAGS_DEP= OPTSCRIPT_DEP=
      - run: make units CI=1 CTAGS_DEP=
