name: swift

on:
  workflow_dispatch:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-14, macos-15]


    runs-on: ${{ matrix.runs-on }}

    strategy:
      fail-fast: false
      matrix:
        pkg: [swiftformat, swiftdraw, swiftly, unxip, xcbeautify, swift-format, swift-section, swiftlint, swift-sh, mist-cli, swift-outdated]

    steps:
      - run: xcrun swift --version

      - uses: SwiftyLab/setup-swift@latest
        if: matrix.runs-on == 'macos-14'

      - run: swift --version

      - run: curl -LO https://github.com/leleliu008/test/releases/download/2023.10.08/xcpkg-0.30.0-macos-15.0-arm64.release.tar.xz
      - run: /usr/bin/bsdtar xf xcpkg-0.30.0-macos-15.0-arm64.release.tar.xz --strip-components=1

      - run: bin/xcpkg about
      - run: bin/xcpkg sysinfo

      - run: bin/xcpkg update
      - run: bin/xcpkg install MacOSX-14.0-arm64/\${{ matrix.pkg }}


