name: Ubuntu

on:
  push:
    branches: [ test-head-instead-of-hexdump ]
  pull_request:
    branches: [ test-head-instead-of-hexdump ]

jobs:
  test:

    strategy:
      fail-fast: false
      matrix:
        version: [18.04, 20.04]

    runs-on: ubuntu-${{ matrix.version }}

    steps:
      - run: |
          [ $(head -c 4 /proc/self/exe) = $(printf '\177ELF') ]
