name: WSL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        distribution: [Ubuntu-20.04, Debian]
        #distribution: [Ubuntu-20.04, Debian, openSUSE-Leap-15.2]

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      # https://github.com/marketplace/actions/setup-wsl
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: ${{ matrix.distribution }}

      - name: Use unix line endings
        shell: bash
        run: |
          # Github's actions/checkout@v2 when run on Windows mangles the line-endings to DOS-style
          # but we're running Linux *on top* of Windows, so we need to not mangle them!
          # https://github.com/actions/checkout/issues/135#issuecomment-602171132
          # https://github.com/actions/virtual-environments/issues/50#issuecomment-663920265
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v2

      - run: |
          printf '%s\n' 'a.rst.1 b.rst.1 c.rst.1' | xargs -I{} basename {} .rst.1
